### ISSUE TITLE
Please invite me to the community

### ISSUE THREAD

**Issue by vinzvinci98** [Surpath-Community/Support#1]
I want to learn more about open-source

**Comment by chraem** [comment]
Invite me to the Surpath Hub Community.

Name: Christine Mae Calumbiran 
Country: Philippines
Discord Username(if exists): cwistin#1464
Additional Context:
     Saw SurPath Hub on Facebook
     Willing to learn, and help 😄

**Comment by lexus654** [comment]
Invite me to the Surpath Hub Community.

Name: Ronald Laz
Country: Philippines
Discord Username(if exists): lexus654#6207
Additional Context:
I saw that sir vins is a campus expert on github and have a community, I feel that this place place will help me grow and learn a lot more  to expand my knowledge about web developing.
